Algoritmo "medidas"

Var

A,B,C,areaQuadrado,areaTriang,areaTrapezio:real


Inicio

escreva("Digite a medida A: ")
leia(A)
escreva("Digite a medida B: ")
leia(B)
escreva("Digite a medida C: ")
leia(C)

areaQuadrado <-  a * a
areaTriang <-  (a * b) / 2
areaTrapezio <- ((a+b)*c)/2

escreval()

escreval("AREA DO QUADRADO = ",areaQuadrado:8:4)
escreval("AREA DO TRIANGULO = ",areaTriang:8:4)
escreval("AREA DO TRAPEZIO = ",areaTrapezio:8:4)



Fimalgoritmo