Algoritmo "quadrado"



Var

   L : real
   A : real
   P : real

Inicio

   escreval("Calcule a Area e Perimetro do quadrado")
   escreval()
   escreval("Qual a comprimento da lateral do Quadrado? ")
   leia(L)
   A <- L * L
   P <- 4 * L
   escreval()
   escreval("A área do seu quadrado é: ",A:5:2)
   escreval()
   escreval("O perimentro do seu quadrado é: ",P:5:2)



Fimalgoritmo